module.exports = {
  STORE_KEY: 'a56z0fzrNpl^2',
  screen :'',
  time : 0,
  BASE_URL: 'http://139.59.76.223/studio54/api/',
  Signin :'Signin',
  Signup :'Signup',
  front_main :'front_main',
  industry :'',
  otp :'otp',
  category : '',
  derive_detail_industry :'derive_detail_industry',
  derive_detail_category : 'derive_detail_category',
  info_number :'',
  info_email : '',
  mainid : '',
  dervie_detail_of_product : 'dervie_detail_of_product',
  media :'media',
  get_settings :'get_settings',
  get_event :'get_event',
  username : '',
  notification:'notification',
  userid : '',
  email :'',
  mobile :'',
  name :'',
  image :'',
  password :'',
  otps : '',
  photos:'photos',
  foreign_id : '', 
  photo_gallery :'photo_gallery',
  partners :'partners',
  booking_event :'booking_event',
  menu:'menu',
  latiude : 0.0,
  longitude : 0.0,
  address : '',

  need_help:'need_help',
  COLOR: {
    ORANGE: '#C50',
    DARKBLUE: '#0F3274',
    LIGHTBLUE: '#6EA8DA',
    DARKGRAY: '#999',
  },
};